language: python

# use container-based infrastructure
sudo: false

deploy:
  provider: pypi
  user: baztian
  password:
    secure: UmPA44q77/kYMaylcsedWlGidShciUj68O6wN+oeAHn8N6x6yI8xDyzC9nwSb9f0309BxfH1EDIbN/6wNX3njh4wHuteySrTcRMb+4q3QsDV1YE6C3v6msNlvZt+Yx9bnmwuQoeXK/QGxDmldiVXnbx3e8wEWmDc7cBP5llPMig=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: baztian/dbapi-compliance

python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'

env:
  matrix:
    - DB_NAME=psycopg DRIVER=psycopg2 PGUSER=postgres

install:
  - if [ -n "$DRIVER" ]; then pip install $DRIVER ;fi

script:
  - python test_${DB_NAME}_dbapi20.py
